service: ULR-server
frameworkVersion: ^3.38.0

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: "us-east-1"
  timeout: 30
  memorySize: 512
  environment:
    NODE_ENV: ${self:provider.stage}
    MONGODB_URI: ${env:MONGODB_URI}

functions:
  api:
    handler: src/index.handler
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000 